### ISSUE TITLE
Improve like efficiency

### ISSUE THREAD

**Issue by WJehee** [NikolayBlagoev/trustchain-superapp#12]
Currently: 1 like per block (might be slow)

- Maybe cache which videos you have liked, then send them in 1 block later (every 1 minute or so)
- Maybe look at which peers are online, send likes immediately if they are online (so you can receive likes faster as a creator)

**Comment by ignjat-ignjat** [comment]
i think we should keep it 1 like per block, as making changes could increase the complexity (ie now we would have to make sure that the signer is not any of the creators of any of the liked videos  or perform more block validation computations etc)

**Comment by WJehee** [comment]
Agreed
